name: OnlinePlayersSQL
main: net.rayherring.OnlinePlayersSQL
version: 1.9.4
dev-url: http://dev.bukkit.org/server-mods/online-players-sql/
depend: [Vault]
softdepend:
- SimplyVanish
commands:
  onl:
    description: Online Players command.
    usage: /onl
